CREATE TABLE IF NOT EXISTS Bookings(
BookingID INT PRIMARY KEY AUTO_INCREMENT,
Date DATETIME,
TableNumber INT,
CustomerID INT,
FOREIGN KEY (CustomerID)
REFERENCES CustomerDetails(CustomerID)
);

CREATE TABLE IF NOT EXISTS Orders(
OrderID INT NOT NULL PRIMARY KEY,
OrderDate DATETIME,
Quantity INT,
TotalCost DECIMAL(5, 4)
);


CREATE TABLE IF NOT EXISTS Menu(
ItemID INT NOT NULL PRIMARY KEY,
ItemType VARCHAR(100) UNIQUE,
ItemName VARCHAR(100) UNIQUE,
ItemDescription Text(100),
Price DECIMAL(5,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CustomerDetails(
CustomerID INT NOT NULl PRIMARY KEY,
CustomerName VARCHAR(100),
ContactDetails VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Staff(
StaffID INT NOT NULL PRIMARY KEY,
Role VARCHAR(100) UNIQUE,
Salary DECIMAL(5, 3)
);
CREATE TABLE IF NOT EXISTS DeliveryStatus(
DeliVeryID INT NOT NULL PRIMARY KEY,
OrderID INT,
FOREIGN KEY (OrderID)
REFERENCES Orders(OrderID)
);
